apiVersion: v1
kind: Service
metadata:
  name: argo-rollouts-metrics
  namespace: argo-rollouts
spec:
  ports:
    - port: 8001
      targetPort: 8001
      name: metrics
  selector:
    app.kubernetes.io/name: argo-rollouts
