apiVersion: v1
kind: Service
metadata:
  name: ecommerce-active
  namespace: default
spec:
  selector:
    app: Ecommerce
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31000  # Keep the same nodePort for the active service
  type: NodePort
