apiVersion: v1
kind: Service
metadata:
  name: nginx-server
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: {{ .Values.nginx.nodePort }}  # Use the NodePort specified in values.yaml
    - name: https
      port: 443
      targetPort: 443
      nodePort: 31001  # Specify a unique NodePort for HTTPS if needed
  selector:
    app: nginx-server



