apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ecommerce-rollout
  namespace: default
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: Ecommerce
  strategy:
    blueGreen:
      activeService: ecommerce-active
      previewService: ecommerce-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 30
  template:
    metadata:
      labels:
        app: Ecommerce
    spec:
      containers:
      - name: ecommerce
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8000

