apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "crm-chart.fullname" . }}-rollout
  namespace: default
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause:
          duration: 30s
      - setWeight: 50
      - pause:
          duration: 60s
      - setWeight: 100
  template:
    metadata:
      labels:
        app: {{ include "crm-chart.name" . }}
    spec:
      containers:
      - name: {{ include "crm-chart.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8000

