apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
spec:
  selector:
    app: Ecommerce
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: {{ .Values.service.nodePort }}
  type: NodePort

