apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Ecommerce
  template:
    metadata:
      labels:
        app: Ecommerce
    spec:
      containers:
      - name: ecommerce-container
        image: ajaff/crm:v1.1
        imagePullPolicy: Always   # Ensure Kubernetes pulls the latest image every time
        ports:
        - containerPort: 8000
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"

---

apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
spec:
  selector:
    app: Ecommerce
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31000
  type: NodePort

