apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Ecommerce
  template:
    metadata:
      labels:
        app: Ecommerce
    spec:
      containers:
      - name: ecommerce-container
        image: ajaff/crm:latest
        ports:
        - containerPort: 8000
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
spec:
  selector:
    app: Ecommerce
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31000
  type: NodePort

