apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: crm-rollout
  namespace: default
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: crm-app
  strategy:
    blueGreen:
      activeService: crm-service-active
      previewService: crm-service-preview
      autoPromotionEnabled: false
  template:
    metadata:
      labels:
        app: crm-app
    spec:
      containers:
      - name: crm-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: crm-service-active
  namespace: default
spec:
  type: NodePort
  selector:
    app: crm-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31001  # Active service on NodePort 31001
---
apiVersion: v1
kind: Service
metadata:
  name: crm-service-preview
  namespace: default
spec:
  type: NodePort
  selector:
    app: crm-app
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8000
      nodePort: 30081  # Preview service on NodePort 30081

