apiVersion: v1
kind: Service
metadata:
  name: crm-service-active-green
  namespace: default
spec:
  selector:
    app: crm-app
    color: green  # Matches green rollout
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

