apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
      - name: ecommerce
        image: "{{ .Values.crmImage.repository }}:{{ .Values.crmImage.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8000

