apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: multi-app-rollout
  namespace: default
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: multi-app  # Generalized label for multiple apps
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause:
          duration: 30s
      - setWeight: 50
      - pause:
          duration: 60s
      - setWeight: 100
  template:
    metadata:
      labels:
        app: multi-app  # Generalized label for multiple apps
    spec:
      containers:
      - name: crm-app
        image: "{{ .Values.crmImage.repository }}:{{ .Values.crmImage.tag }}"
        ports:
        - containerPort: 8000  # CRM app port
     

