apiVersion: v1
kind: Service
metadata:
  name: rollouts-metrics
  namespace: crm-rollout
spec:
  ports:
    - port: 8090
      targetPort: 8090
      name: metrics
  selector:
    app.kubernetes.io/name: argo-rollouts
