apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
  namespace: default ##
spec:
  type: NodePort
  selector:
    app: ecommerce
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31000
  #type: NodePort

