apiVersion: apps/v1
kind: Deployment
metadata:
  name: dms-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dms
  template:
    metadata:
      labels:
        app: dms
    spec:
      containers:
      - name: dms
        image: "{{ .Values.dmsImage.repository }}:{{ .Values.dmsImage.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8282

