apiVersion: v1
kind: Service
metadata:
  name: dms-service
  namespace: default ##
spec:
  type: NodePort
  selector:
    app: dms
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
  #type: NodePort

