apiVersion: v1
kind: Service
metadata:
  name: dms-service
  namespace: default
spec:
  type: LoadBalancer  # Change from NodePort to LoadBalancer
  selector:
    app: dms-app
  ports:
    - protocol: TCP
      port: 80         # Change external port to 80 for HTTP traffic
      targetPort: 8282  # Match the container port defined in the Rollout

