apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring  # Change this if you have a different namespace
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
      - name: node-exporter
        image: prom/node-exporter:latest # You can check for the latest version
        ports:
        - containerPort: 9100
          name: metrics
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      tolerations:
      - key: "node-role.kubernetes.io/master"  # Allow running on master nodes if needed
        effect: "NoSchedule"
