apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "crm-chart.fullname" . }}
  labels:
    {{- include "crm-chart.labels" . | nindent 4 }}
spec:
  replicas: 4
  selector:
    matchLabels:
      app: {{ include "crm-chart.name" . }}
  strategy:
    canary:
      steps:
        - setWeight: 20
          pause:
            duration: 30s
        - setWeight: 50
          pause:
            duration: 60s
        - setWeight: 100
  template:
    metadata:
      labels:
        app: {{ include "crm-chart.name" . }}
    spec:
      containers:
        - name: crm-chart
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8000

