apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-metrics
  namespace: ingress-nginx
spec:
  ports:
    - port: 10254
      protocol: TCP
      targetPort: 10254
      nodePort: 30001  # Expose it via NodePort
  selector:
    app.kubernetes.io/name: ingress-nginx
  type: NodePort
